-- AlterTable
ALTER TABLE "GroupPlayer" ADD COLUMN     "groupElo" DOUBLE PRECISION NOT NULL DEFAULT 1000;

-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "globalElo" DOUBLE PRECISION NOT NULL DEFAULT 1000;
